### ISSUE TITLE
Readthedocs 404s

### ISSUE THREAD

**Issue by zacanger** [demberto/PyFLP#10]
It's not a huge deal since the docs are in the repo anyway, but it looks like the mkdocs build failed at some point. Works fine testing locally, but lots of 404s on the actual RTFD site.

<img width="786" alt="screen_shot_2022-07-15_at_20 06 35" src="https://user-images.githubusercontent.com/12520493/179334657-6c4444e3-1661-41f7-9251-f8895f118851.png">

**Comment by zacanger** [comment]
Whoops, nevermind — it's not the mkdocs build readthedocs, it's just a link in the README. I'll put in a PR for that.

**Comment by demberto** [comment]
@all-contributors please add @zacanger for doc
