### ISSUE TITLE
🐞 Channel.group fails, KWProp doesn't seem to be set up properly for DisplayGroup

### ISSUE THREAD

**Issue by BilliumMoto** [demberto/PyFLP#100]
### Describe the issue

![image](https://user-images.githubusercontent.com/4618068/201478497-d7ff0fec-1f4d-4894-b0a1-86fe20a7c201.png)

### What version of PyFLP are you using?

2.0.0a5.post

### What code caused this issue?

```python3
import pyflp as pf
test_project = Path(...)
flp = pf.parse(test_project)
print(flp.version)
channels = flp.channels
channel = channels[0]
channel.group
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BilliumMoto** [comment]
For others who see this, here's a viable workaround:
```
def get_group(channel_rack: ChannelRack, channel: Channel) -> str:
    group_names = list(channel_rack.groups)
    group_index = channel.events.get(ChannelID.GroupNum)[0].value
    return group_names[group_index].name
```

**Comment by demberto** [comment]
Fixed in latest commit. Will make a release once a few more things get added.
