### ISSUE TITLE
🐞 `Channel.plugin` fails due to base class type param check

### ISSUE THREAD

**Issue by BilliumMoto** [demberto/PyFLP#101]
### Describe the issue

Key line is in pyflp.plugin: 412, where get_args(ptype) may return an empty tuple, resulting in this error:
```
  File "...\lib\site-packages\pyflp\plugin.py", line 412, in __get__
    if isinstance(ins.events.first(PluginID.Data), get_args(ptype)[0]):
IndexError: tuple index out of range
```

### What version of PyFLP are you using?

2.0.0a5.post

### What code caused this issue?

```python3
# A project with just one patcher or VST instrument channel
proj = parse(project_file)
channels = proj.channels
channel = list(channels)[0]
print(channel.plugin)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by demberto** [comment]
I think it is `EventTree.first` called on an empty dict key internally. Will check tomorrow.

**Comment by demberto** [comment]
I can reproduce this issue
