### ISSUE TITLE
🐞 Custom enums broken in construct-typing 0.5.4

### ISSUE THREAD

**Issue by ttaschke** [demberto/PyFLP#111]
### Describe the issue

Running `tox` for testing results in the following `TypeError` being thrown in `_VSTPluginEventID`:
```
py39: commands[0]> coverage run -m pytest
ImportError while loading conftest '/python_project/pyflp/tests/conftest.py'.
tests/conftest.py:8: in <module>
    import pyflp
pyflp/__init__.py:58: in <module>
    from .plugin import PluginID, get_event_by_internal_name
pyflp/plugin.py:204: in <module>
    class _VSTPluginEventID(ct.EnumBase):
/usr/lib/python3.9/enum.py:273: in __new__
    enum_member.__init__(*args)
E   TypeError: __init__() takes 2 positional arguments but 3 were given
```

This bug was introduced by the automatic merge https://github.com/demberto/PyFLP/pull/110 (Note: Maybe it would be safer to have a human check these kind of updates before merging?) and seems to be caused by the following change in `construct-typing`:
https://github.com/timrid/construct-typing/commit/916349f876c23e191973eb17bbb969e478858ed7#diff-6f0a7161c5863ec910bbe7e7a9d960e28d1edba2653cef2bac7fe967082a42c2R51-R55

### What version of PyFLP are you using?

Newest master branch version

### What code caused this issue?

```python3
Running tox
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ttaschke** [comment]
Memo:

A constructor was introduced to `ct.EnumBase` that now gets called with the parameters from `_VSTPluginEventID`'s __new__ method
```
    def __init__(self, val: t.Union[EnumValue, int]):
        if isinstance(val, EnumValue):
            self.__doc__ = val.__doc__
        else:
            self.__doc__ = ""
```

https://github.com/demberto/PyFLP/blob/master/pyflp/plugin.py#L190-L194
```
@enum.unique
class _VSTPluginEventID(ct.EnumBase):
    def __new__(cls, id: int, ascii: bool = False):
        obj = int.__new__(cls, id)
        obj._value_ = id
        setattr(obj, "ascii", ascii)
        return obj
```

**Comment by demberto** [comment]
Hmm. Enums underwent some big changes in 3.11
