### ISSUE TITLE
🐞Can't unlock Sytrus 

### ISSUE THREAD

**Issue by Fire-Cube** [demberto/PyFLP#153]
### Describe the issue

Hello guys

Ich use this project to unlock my FL Studio 20 Files.
Sadly I can't unlock Sytrus with this script.

Can you help me please?

### What version of PyFLP are you using?

2.1.0

### What code caused this issue?

```python3
import pyflp

project = pyflp.parse("C:\\Users\\ben7\\OneDrive\\Dokumente\\Image-Line\\FL Studio\\Projects\\X6.flp")
project.licensed = True
project.registered = True

for instrument in project.channels.instruments:
    instrument.demo_mode = False

for insert in project.mixer:
    for slot in insert:
        if slot.plugin is not None:
            slot.plugin.demo_mode = False

pyflp.save(project, "C:\\Users\\ben7\\OneDrive\\Dokumente\\Image-Line\\FL Studio\\Projects\\X6_u.flp")
```
```


### Screenshots, Additional info

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by demberto** [comment]
This tutorial haa been updated https://pyflp.readthedocs.io/en/latest/handbook.html#unlocking-demo-version-flps

Feel free to reopen this issue if it fails.

**Comment by Fire-Cube** [comment]
Thanks. This works but there is a typo in the first variable "instument".

**Comment by demberto** [comment]
> 

Ahh thanks :)
