### ISSUE TITLE
✨ Additional research into unknown fields

### ISSUE THREAD

**Issue by ashduino101** [demberto/PyFLP#185]
### Describe the feature

Hello,

If you're interested, I've been working on [a 010 editor binary template](https://www.sweetscape.com/010editor/manual/IntroTempScripts.htm) to help reverse engineer FLP event formats and data structures. I've already added some structures that haven't been implemented in this library yet, so this might be useful to you. The template is available as a [GitHub gist](https://gist.github.com/ashduino101/47f9cd7239bff11f1b25a7d0376eb452).

### What version of PyFLP are you using?

Latest source (v2.2.1+)

### Screenshots, Additional info

![image](https://github.com/demberto/PyFLP/assets/67023707/f15df5e1-094f-446a-8533-cfbbf5e7bc5e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by meint52** [comment]
Very nice! Im using ImHex since it's free, do you know if there is an easy way to use this template in there?

**Comment by demberto** [comment]
Nice work, I'll add info about this to the README. Just a small thing I noticed, note size wasn't always 24, I have found FLPs having Note event sizes of a multiple of 16.

Can you give some brief summary of which fields or events you have discovered not present in PyFLP? If its an entirely new event ID can you also add something about it in #34?
