### ISSUE TITLE
🐞 FL 12 `fx.start` - `LogNormal` (duplicate)

### ISSUE THREAD

**Issue by happymimimix** [demberto/PyFLP#187]
### Describe the issue

[FreshStart.zip](https://github.com/demberto/PyFLP/files/13850059/FreshStart.zip)
I made this project in fl studio 12.3 for testing the efficiency of pyflp and it's ability to process Black MIDI. 
I'm using pypy 3.9 with the latest pyflp. 
Can you assist me with this issue please. 
What did I do wrong? Or is this a bug of pyflp? 

### What version of PyFLP are you using?

pyflp-2.2.1-py3

### What code caused this issue?

```python3
proj = pyflp.parse("E:\\MIDI\\FreshStart.flp")
```

### Screenshots, Additional info

![image](https://github.com/demberto/PyFLP/assets/107282563/2f6b0761-36a4-47ad-9447-e0c9fa5645c6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by demberto** [comment]
Yes this is an issue. Check [this comment](https://github.com/demberto/PyFLP/issues/142#issuecomment-1545684431) for a solution.

**Comment by sudo-000** [comment]
Why didn't YOU just change that code and let it be like that when you release it? If it help keeping the program less buggy?

**Comment by happymimimix** [comment]
@demberto Replacing that line in channel.py does not fix the problem.

**Comment by sudo-000** [comment]
@demberto Replacing that line in channel.py does not fix the problem.

**Comment by happymimimix** [comment]
![image](https://github.com/demberto/PyFLP/assets/107282563/6de4482c-2495-47c8-b067-cca17a2ce8f8)
