### ISSUE TITLE
🐞 FLPEdit should be updated to an SDK-Project

### ISSUE THREAD

**Issue by SilverShepherd** [demberto/PyFLP#191]
### Describe the issue

I tried FLPEdit like mentioned in the documentation.
But it doesn't seem to work out of the box like mentioned.
My Visual Studio couldn't run it, because it is not an SDK Style Visual Studio Project. 
It was a pretty comlex of updating the project to be in SDK, so for other people it would be cool if the downloadable FLPEdit-Project would be directly in the SDK Format.

Here is my SDK convert of the FLPEdit-CodeProject (for interested people)
[FLPEdit (SDK Converted).zip](https://github.com/demberto/PyFLP/files/15283125/FLPEdit.SDK.Converted.zip)

### What version of PyFLP are you using?

2.2.2dev6

### What code caused this issue?

```python3
.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by demberto** [comment]
FLPEdit isn't my code. The person who wrote it deleted it from Github.
