### ISSUE TITLE
🐞 Iterating over the slots of an `Insert` results in an infinite loop

### ISSUE THREAD

**Issue by ttaschke** [demberto/PyFLP#53]
I am not 100% sure yet, if this is just a problem with how I am using PyFLP, but it seems like iterating over slots in an insert results in an infinite loop.
```
for slot in project.mixer[1]:
    ...
```
Iterating over inserts works fine on the other hand.

Related code memo:
https://github.com/demberto/PyFLP/blob/master/pyflp/mixer.py#L438-L457

**Comment by demberto** [comment]
Hmm, need to check

**Comment by ttaschke** [comment]
@demberto 
Awesome, thanks! 
Works fine now. 

```
>>> project.mixer[0][0]
Unnamed slot (Fruity Fast Dist)

>>> for slot in project.mixer[1]:
...     type(slot)
...
<class 'pyflp.mixer.Slot'>
<class 'pyflp.mixer.Slot'>
<class 'pyflp.mixer.Slot'>
<class 'pyflp.mixer.Slot'>
<class 'pyflp.mixer.Slot'>
<class 'pyflp.mixer.Slot'>
<class 'pyflp.mixer.Slot'>
<class 'pyflp.mixer.Slot'>
<class 'pyflp.mixer.Slot'>
<class 'pyflp.mixer.Slot'>
<class 'pyflp.mixer.Slot'>
```

**Comment by demberto** [comment]
Nice catch, this one. *And now a mention to* #6
