### ISSUE TITLE
📌 Implement structs with the `construct` library

### ISSUE THREAD

**Issue by demberto** [demberto/PyFLP#70]
`construct` is a Python library especially made for parsing binary structs. Using it would make parsing structures of any kind immensely simpler, it would take away all the voodoo I do with metaclass of `StructBase`.

While `construct` itself is nothing new, I need to experiment with it to retrofit it inside the existing event system. Maybe I could use a `construct.Struct` to replace all `BytesIOEx` instances in `DataEventBase`?

**Comment by demberto** [comment]
@ttaschke Just a heads up, I have been having success with `construct`. I have replaced all `StructBase` with equivalent `construct.Struct`. It maybe possible to use multiple structs for different layouts after all, so a modification of `StructBaseEvent` won't be needed, *mention to #42*

**Comment by ttaschke** [comment]
@demberto 
Thanks for the heads-up.
https://github.com/construct/construct 👀  I see.. interesting!
