### ISSUE TITLE
🐞 `pan` var in `PatternNote` limited to -64 & 64 but some flp exceed these values

### ISSUE THREAD

**Issue by Naaikho** [demberto/PyFLP#71]
### Describe the issue

the minimum and maximum values assigned to the pattern pan can be quickly exceeded by certain projects, which returns a value error.

### PyFLP version

1.1.1

### What code caused this issue?

```python3
import pyflp
import sys, os

os.chdir(sys.path[0])

parse = pyflp.Parser()

l = parse.parse("random.flp")
```

### Screenshots, Additional info

![image](https://user-images.githubusercontent.com/62458713/193502083-c0de1c1e-38cf-452d-9164-a1819f9caf34.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by demberto** [comment]
Yea, I know this issue. Was fixed in unreleased 1.1.2. However, you should prefer a pre-release version. Its way more stable than 1.1.1.

Install instructions in README. Docs are linked on the main page.
