### ISSUE TITLE
VST GUID non ASCII; MIDI channel 128

### ISSUE THREAD

**Issue by SilasNiewierra** [demberto/PyFLP#8]
When I try to run the provided example,
I get the following error.
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 1: ordinal not in range(128)`

Therefore neither this package, nor FLPInspect or FLPInfo work.

Can you please have a look at this?

**Comment by demberto** [comment]
The FLP seems corrupted, can you please provide a traceback and the FLP itself?

You are the first user of my library probably, thanks its motivating :))

**Comment by SilasNiewierra** [comment]
I think I found the reason, or another bug 😁 
I tried to recreate the problem by creating an empty file (which works 👍 ) and then add plugins and samples till I reach the .flp which was broken.
I found out that if you drag a MIDI file onto a channel, your analyzer will crash with:
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/55000832/177693087-594d7461-87d2-4ef0-b165-03a314c55bc8.png">
Since both of the errors have that `128` in them, I suspect they both come from the same issue.

**Comment by demberto** [comment]
Ok, another bug. But this is not related to the first one at all. The MIDI channel limited to 15 are the 16 colors you can choose for your notes. Now it seems there's another use case for them too. I will try to reproduce this issue, if I can't maybe you can send me the `test.flp`?

The GUID error you ran with earlier, it is exclusively used by Waves plugins AFAIK. Can you check your `warm.flp` for any Waves plugins?

I think this definitely makes a point to improve the error handling. I could add more info about what insert or channel failed to parse for example.

**Comment by SilasNiewierra** [comment]
Hi there,
I was able to get what I wanted by using node.js and a custom flp-parser library.
However, regarding this issue: I didn't use Waves plugins for the test file but kHS Plugins and two Serum instances.
I hope this helps 😄

**Comment by tochibedford** [comment]
Hey! ran into same issue when I opened 1 flp but didn't occur for other flps:
<img width="798" alt="Screenshot 2022-07-09 at 03 03 45" src="https://user-images.githubusercontent.com/34871260/178087658-af1dc032-0559-4572-a3da-f3b5de6a0123.png">

Also I should note, I just spent the last 4 hours writing a parser so I could quickly look through the samples used in an flp, only to find out someone already did it (you), so thank you!

**Comment by demberto** [comment]
@tochibedford I will fix this issue ASAP. You can reach me via email: demberto@protonmail.com. I check my mails often so I reply as soon as I can generally :)

**Comment by demberto** [comment]
@tochibedford @SilasNiewierra Please test your FLPs with v1.1.1

You can run

```
pip install --upgrade pyflp
```

to update to PyFLP 1.1.1

**Comment by demberto** [comment]
Closing this issue due to lack of response, bugs fixes in v1.1.1

**Comment by demberto** [comment]
@all-contributors please add @zacanger for bug
