### ISSUE TITLE
🐞 Legacy event used for `TimeStretching.time`

### ISSUE THREAD

**Issue by jubabrut** [demberto/PyFLP#86]
### Describe the issue

I open a standard project with sampler (with sample), I only parse channels items, I saved it with a new name.
But I can't reopen it again, FL Studio displays an error.

```
import pyflp
import os

current_dir = os.path.dirname(os.path.realpath(__file__)) + "\\"

project = pyflp.parse(current_dir + "test.flp")

for item in project.channels.samplers:
	print(item.stretching)

pyflp.save(project, current_dir + "test2.flp")
```

### What version of PyFLP are you using?

2.0.0a4

### What code caused this issue?

```python3
print the stretching informations generates an error on the project saving
```

### Screenshots, Additional info

![image](https://user-images.githubusercontent.com/116581210/197570394-596d796a-8498-4272-9758-9f80cba8d748.png)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by demberto** [comment]
I cannot reproduce this issue. Can you send me the FLP you are encountering this issue with?

Also,
- Are you sure the FLP isn't already corrupted?
- Do you get any sort of warnings?
- What FL Studio version are you using?

There is infact a test for null checks in the test suite, which exactly checks this - whether an FLP gets modified if saved without any modifications. It doesn't cause problems with the test FLP.

**Comment by jubabrut** [comment]
[PyFLP test.zip](https://github.com/demberto/PyFLP/files/9858302/PyFLP.test.zip)

Find in attached the PY file and the original FLP file.
I'm on Windows 10.
The FLP file is very basic (only an audio sample provided by FL Studio)

I think I found the problem.
The problem appears only when I try to access to the stretching informations of a channels.samplers.
Only print information generates the problem.

**Comment by jubabrut** [comment]
Moreover when I try to set a "time stretching" data, it generates an exception.
Maybe it is a collateral problem.

```
project = pyflp.parse(current_dir + "test.flp")

for item in project.channels.samplers:
	item.stretching.time = 1.0
```

```
Traceback (most recent call last):
  File "C:\Users\Musique\Desktop\PyFLP test\flp.py", line 13, in <module>
    item.stretching.time = 1.0
  File "C:\Users\Musique\AppData\Local\Programs\Python\Python39\lib\site-packages\pyflp\_descriptors.py", line 122, in __set__
    raise PropertyCannotBeSet(*self._ids)
pyflp.exceptions.PropertyCannotBeSet: Event(s) (<ChannelID.StretchTime: 140>,) was / were not found
```

**Comment by demberto** [comment]
Ok so these are 2 bugs:
1. The FLP doesn't get saved properly, this was due to a bug in `pyflp._events.EventTree.subdict` not using a sorted list. I have **already fixed** it in latest commits, but there's something else broken. I will notify you when I push all the commits.
2. `TimeStretching.time` reads from legacy event, no longer used in newer versions of FL Studio. This one I need to fix.

**Comment by demberto** [comment]
@jubabrut I have fixed the bugs in latest commits, you can install the latest version from git directly until I make the next release

**Comment by jubabrut** [comment]
everything works, great job, thanks
