### ISSUE TITLE
🐞 `ChannelRack.__iter__` fails to yield the only `Channel`

### ISSUE THREAD

**Issue by jubabrut** [demberto/PyFLP#90]
### Describe the issue

I created an audio channel with an audio track.
This channel is correctly count with "project.channel_count"
But when I try to access to this channel, nothing happens

```
import pyflp
import os

# Get the current directory on Windows
current_dir = os.path.dirname(os.path.realpath(__file__)) + "\\"

# Open the FLP project
project = pyflp.parse(current_dir + "test.flp")

print("Channel count: " + str(project.channel_count))

print("start")
for chan in project.channels:
	print(chan)
print("end")
```

### What version of PyFLP are you using?

last commit (26th oct 22)

### What code caused this issue?

```python3
project.channel
```

### Screenshots, Additional info

![image](https://user-images.githubusercontent.com/116581210/198119601-4e2a337b-cd96-4092-a3bb-9e6c4bfcf810.png)

![image](https://user-images.githubusercontent.com/116581210/198119638-267fc0b3-8287-4d72-b616-759684a08ec4.png)

[PyFLP test 2.zip](https://github.com/demberto/PyFLP/files/9873194/PyFLP.test.2.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by demberto** [comment]
@jubabrut check again, should work now

**Comment by jubabrut** [comment]
problem solved, thanks
