### ISSUE TITLE
🐞 `TrackID.Name` events are grouped incorrectly

### ISSUE THREAD

**Issue by jubabrut** [demberto/PyFLP#96]
### Describe the issue

I created this FLP file

![image](https://user-images.githubusercontent.com/116581210/198349044-d843f757-cef5-49ee-a671-99f652d08045.png)

But when I parse tracks with this code
```
for track in project.arrangements.current.tracks:
	print(track)
```

The name doesn't match with correct track

```
Track (name=Cymbal, index=1, 1 items)
Track (name=Kick, index=2, 0 items)
Track (name=Snare, index=3, 2 items)
Track (name=None, index=4, 0 items)
Track (name=None, index=5, 3 items)
```

### What version of PyFLP are you using?

last commit (27th oct 22)

### What code caused this issue?

```python3
-
```

### Screenshots, Additional info

Find below FLP and PY files

[PyFLP test 3.zip](https://github.com/demberto/PyFLP/files/9881480/PyFLP.test.3.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by demberto** [comment]
Nice that you noticed, fix on the way :))

**Comment by demberto** [comment]
Fixed.

**Comment by jubabrut** [comment]
It works thanks
