### ISSUE TITLE
✨ Possible to change length, position and offset of an audio sample

### ISSUE THREAD

**Issue by jubabrut** [demberto/PyFLP#97]
### Describe the feature

When I try to change position or length of an audio clip in the Playlist, with that code

```
tracks = [track for track in project.arrangements.current.tracks]
tracks[2].__getitem__(0).position = 100
```

I have this error
`pyflp.exceptions.PropertyCannotBeSet: Event(s) () was / were not found`

It will be interesting to be able to change the position, the length and the offset of an audio clip

![image](https://user-images.githubusercontent.com/116581210/198353505-a1ced01a-3a48-4e63-87ef-101bd6552652.png)

### What version of PyFLP are you using?

last commit (27th oct 22)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by demberto** [comment]
While actually I have not implemented this, the exception was a result of a bug in here:

https://github.com/demberto/PyFLP/blob/50349106a3bf355a294398808f4ba56f33cee443/pyflp/_descriptors.py#L121-L129

This was quite a big bug making nearly everything unsettable. This reminds me of testing the setters as well.

**Comment by demberto** [comment]
Technically it is settable via the huge `PlaylistEvent` but that needs low-level API knowledge

**Comment by demberto** [comment]
Done, implemented in latest commits. New release comming soon 🎉

**Comment by jubabrut** [comment]
Thanks
perfect it works too
what is the difference between the length and the offset (end minus start) ?

**Comment by demberto** [comment]
Start Offset:

![start_offset](https://user-images.githubusercontent.com/65948403/198401304-6be9e6ed-5ae1-4e81-ab7c-916e2a97f759.gif)

Length is the length of the item as it is visible to you in the playlist.
End offset is the internal position from the end of a sample or a pattern. Now you might think that `start_offset` + `length` is enough for that, why another field?

And the answer to this is, I don't know myself 😄 FLP is a weird format.

**Comment by demberto** [comment]
@jubabrut Will it possible for you to test PyFLP and find out bugs and suggest new ideas like these? Doing so will be a great help for me and will fasten the release cycle. A stable version will be ready sooner 🤗

**Comment by jubabrut** [comment]
For the moment I try PyFLP and discover all features, that's why I find some bugs on different functionnalities.
But yes I wiil try to pass more time on this project in order to help you to increase the release cycle and find bugs.

**Comment by demberto** [comment]
> Do you know how the offset value is construct ? Right now I don't fina logic with a value like 1174289603
> 
> Did you notice a full audio clip offset are (-1082130432, -1082130432), so weird

I need to take a look at it, maybe its incorrectly parsed, maybe it is a float, maybe it is not an absolute value at all.

> What is your goal with this library? Because it is a huge work

At first, I aim to make all existing structures parseable and editable. I try to find the representations of various quantities like the `TimeStretching.time` feature you had problems with. That is the hardest part.

I am also looking at the ability to clone or add certain entities like channels or MIDI notes for example. Once things like channels can be cloned, you can play with the values and modify them to your liking.

Some particular areas needing work are:
- MIDI and Internal controllers
- Patterns
- Automation clips

I generally try to add features when I am genuinely sure that the integrity of existing data is not compromised. PyFLP guarantees to not touch the data you didn't modify. FL studio on the other hand, rewrites everything from scratch, since it knows how the format works entirely.

**Comment by jubabrut** [comment]
Ok because I really don't understand how to use offset value.
Look at this example.
[PyFLP test 4.zip](https://github.com/demberto/PyFLP/files/9887227/PyFLP.test.4.zip)

![image](https://user-images.githubusercontent.com/116581210/198557808-f046bc76-3fb2-4d45-9e63-acb2a617f6aa.png)

```
Track 0
Length: 1536
(-1082130432, -1082130432)
Difference: 0

Track 1
384
(0, 1134572607)
Difference: 1134572607

Track 2
384
(1134572607, 1142961215)
Difference: 8388608

Track 3
384
(1142961215, 1148210782)
Difference: 5249567

Track 4
384
(1148210782, 1151349637)
Difference: 3138855
```

**Comment by demberto** [comment]
> (A bug is open by Image Line because strange behovior happens when you switch a sample with different BPM. Position, length and offset change randomly).

FL has grappled with timing issues since eternity 😄

> Ok because I really don't understand how to use offset value.

I think its interpreted incorrectly (might be a float, might be PPQ dependant, dunno). But atleast the start, end values seem to match up with the arrangement. I will take a look at this.

**Comment by jubabrut** [comment]
I really don't understand how to use to_bytes
it gives me something like

```
Track 1
b'\x00\x00\x00\x00'
b'?4\xa0C'

Track 2
b'?4\xa0C'
b'?4 D'

Track 3
b'?4 D'
b'^NpD'
```

**Comment by demberto** [comment]
Yes sorry I meant
```py
tuple(int.to_bytes(value, 4, "little"))
```

which will give you something like
```py
(1, 2, 3, 4)
```

Now you get 4 numbers instead of one and maybe it can help you find out some relation between the arrangement and them.
Although I don't think there's anything useful out of these numbers, maybe they represent a quantity I don't know about.

**Comment by jubabrut** [comment]
do other python libraries provide the same result for offsets?

**Comment by demberto** [comment]
Wdym? There are no *other* libraries which can parse FLPs to the best of my knowledge. This implementation of playlist item offsets is from MonadGroup's FLParser which parses it as a float  or uint32 as well.
I think i initially parsed it as float as well and got similar results. The playlist items are locked to the resolution of the PPQ (unlike automation points, which are completely free), so I think float would be too accurate for that and waste space

**Comment by jubabrut** [comment]
I was just thinking about FLParser but I didn't test that library
thanks again for the time and your patience

**Comment by jubabrut** [comment]
From my first constatation, the offsets values indicate the time where to cut the sample, by not taking account the arrangement, the general bpm or the time stretching.
See below it is the same samples by the second one is time stretched but cuted on the same location.
And the offset end values are the same.

![image](https://user-images.githubusercontent.com/116581210/198825951-a51ba1e7-db44-47b3-900b-4e104114433c.png)

**Comment by demberto** [comment]
Interesting
